repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: check-docstring-first
          - id: check-json
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: "v8.49.0" # Use the sha / tag you want to point at
      hooks:
          - id: eslint
            additional_dependencies:
                - "@vue/eslint-config-prettier@8.0.0"
                - "@vue/eslint-config-typescript@12.0.0"
                - eslint-plugin-vue@9.17.0xx
            types: [file]
            types_or: [javascript, jsx, ts, tsx, vue]
